// Generated by: npm run type-gen
// This file is auto-generated by the Supabase CLI. Do NOT edit manually.
// Run `npm run type-gen` after Story 1.4 to populate with real types.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
